#pragma once

#include <windows.h>
#include "common.h"

class ZSysInterface
{
public:
    ZSysInterface();

    virtual bBool UnkFunc0() = 0;
    virtual ~ZSysInterface() = 0;
    virtual int InitializeResources() = 0;
    virtual bBool ProcessWindowMessages(HWND) = 0;
    virtual void UnkFunc3() = 0;
    virtual LRESULT DispatchAndAllocateMessage(WPARAM, const void *, int) = 0;
    virtual char UnkFunc5(const char *, int) = 0;
    virtual void ChangeDisplaySettings() = 0;
    virtual char PrintStatus(char) = 0;
    virtual int UnkFunc8() = 0;
    virtual void UnkFunc9() = 0;
    virtual void *InitActionMap() = 0;
    virtual void FreeActionMap() = 0;
    virtual uint8_t *UnkFunc12() = 0;
    virtual void UnkFunc13() = 0;
    virtual char UnkFunc14(int) = 0;
    virtual char UnkFunc15(int) = 0;
    virtual char UnkFunc16(int) = 0;
    virtual bBool IsKeyPressed(int p_vKey) = 0;
    virtual char UnkFunc18(int) = 0;
    virtual char UnkFunc19(int) = 0;
    virtual WORD UnkFunc20(UINT) = 0;
    virtual char **UnkFunc21(char **, int) = 0;
    virtual BOOL SetWindowTitle(const char *) = 0;
    virtual int UnkFunc23(int) = 0;
    virtual int UnkFunc24() = 0;
    virtual void UnkFunc25(const char *) = 0;
    virtual void UnkFunc26(const char *) = 0;
    virtual void UnkFunc27(const char *) = 0;
    virtual void UnkFunc28(const char *) = 0;
    virtual void UnkFunc29(const char *) = 0;
    virtual char **UnkFunc30(char **, int) = 0;
    virtual int UnkFunc31() = 0;
    virtual void GenerateUniqueFilename() = 0;
    virtual void UnkFunc33() = 0;
    virtual double UnkFunc34() = 0;
    virtual int UnkFunc35() = 0;
    virtual int64_t UnkFunc36() = 0;
    virtual void UnkFunc37() = 0;
    virtual void Sleep(DWORD p_milliseconds) = 0;
    virtual void Init(char *p_cmdLineArgs) = 0;
    virtual char Restart(int) = 0;
    virtual void UnkFunc40(int, int, int) = 0;
    virtual void UnkFunc41(int, int) = 0;
    virtual int UnkFunc42(char *) = 0;
    virtual char UnkFunc43(int) = 0;
    virtual void UnkFunc44() = 0;
    virtual int UnkFunc45(int, int) = 0;
    virtual void UnkFunc46(int, int, int, int, char *, ...) = 0;
    virtual void UnkFunc47(int, int, int, char *, ...) = 0;
    virtual void UnkFunc48(int, char *, ...) = 0;
    virtual int UnkFunc49(int) = 0;
    virtual int UnkFunc50(int) = 0;
    virtual int UnkFunc51(int) = 0;
    virtual int GetConsole() = 0;
    virtual int UnkFunc53(int, int, int) = 0;
    virtual int UnkFunc54(int, int) = 0;
    virtual double UnkFunc55(int, int) = 0;
    virtual double UnkFunc56(int, int) = 0;
    virtual int UnkFunc57(const void *, unsigned int, int, const char *, int) = 0;
    virtual char UnkFunc58(char *, unsigned int, int, int, int) = 0;
    virtual int UnkFunc59(int, int, int, int, int) = 0;
    virtual int UnkFunc60(int, int) = 0;
    virtual int UnkFunc61() = 0;
    virtual void UnkFunc62(const char *) = 0;
    virtual void UnkFunc63(const char *) = 0;
    virtual void UnkFunc64() = 0;
    virtual void UnkFunc65() = 0;
    virtual ZSysInterface *UnkFunc66(const void *, signed int, int, int) = 0;
    virtual uint64_t UnkFunc67(int, int) = 0;
    virtual FARPROC UnkFunc68(int) = 0;

    uint8_t m_currentState;
    uint8_t m_previousState;
    uint8_t m_isPaused;
    uint8_t unkByte4;
    uint8_t m_disablePack;
    uint8_t m_stereoView;
    uint8_t m_antiAlias;
    uint8_t m_disableDXT;
    uint8_t m_disablePAL;
    uint8_t m_disableWBuffer;
    uint8_t m_disableMultiTexture;
    uint8_t unkByte12;
    uint8_t m_disableLight;
    uint8_t m_trilinearFiltering;
    uint8_t m_windowFlag;
    uint8_t unkByte12_1;
    uint8_t m_disableHWTnl;
    uint8_t m_enableEMBM;
    uint8_t m_enableTripleBuffering;
    uint8_t m_debugVideo;
    uint8_t unkByte12_3;
    int m_resWidth;
    int m_resHeight;
    int unkInt3;
    int unkInt4;
    int m_colorDepth;
    int unkInt6;
    int m_refreshRate;
    int unkInt6_1;
    int m_startUpperPosX;
    int m_startUpperPosY;
    int m_backColor;
    int m_anisotropy;
    int m_shadowDetail;
    uint8_t m_noBlood;
    uint8_t m_pathFinderInof;
    uint8_t m_enableScriptRTC;
    uint8_t m_disableOptions;
    int m_textureResolution;
    int m_levelOfDetail;
    int unkInt14;
    int unkInt15;
    int unkInt16;
    int unkInt17;
    uint8_t unkPad2[120];
    int unkInt18;
    int unkInt19;
    uint8_t unkPad3[120];
    int unkInt20;
    int unkInt21;
    uint8_t unkPad4[120];
    int unkInt22;
    int unkInt23;
    uint8_t unkPad5[120];
    int unkInt24;
    int unkInt25;
    uint8_t unkPad6[120];
    int m_defaultScene;
    int unkInt26;
    uint8_t unkPad7[120];
    int unkInt27;
    int unkInt28;
    uint8_t unkPad8[120];
    int unkInt29;
    int unkInt30;
    uint8_t unkPad9[120];
    int unkInt31;
    int unkInt32;
    uint8_t unkPad10[120];
    int unkInt33;
    int unkInt34;
    uint8_t unkPad11[120];
    int unkInt35;
    int unkInt36;
    uint8_t unkPad12[120];
    int unkInt37;
    int unkInt38;
    uint8_t unkPad13[120];
    int m_animFile;
    int unkInt40;
    uint8_t unkPad14[120];
    int unkInt41;
    int unkInt42;
    uint8_t unkPad15[120];
    int unkInt43;
    int unkInt44;
    uint8_t unkPad16[120];
    int unkInt45;
    int unkInt46;
    uint8_t unkPad17[120];
    int unkInt47;
    int unkInt48;
    uint8_t unkPad18[120];
    int unkInt49;
    int unkInt50;
    uint8_t unkPad19[120];
    int unkInt51;
    int unkInt52;
    uint8_t unkPad20[120];
    int unkInt53;
    int unkInt54;
    uint8_t unkPad21[120];
    int unkInt55;
    int unkInt56;
    int unkInt58;
    int unkInt59;
    float m_enableTimers;
    float m_enableDebugOptions;
    int m_info;
    HWND m_dllHinst;
    int unkInt63;
    HWND m_messageWindow;
    HWND m_mainHwnd;
    int unkInt66;
    int unkInt67;
    int unkInt68;
    int unkInt69;
    int unkInt70;
    int unkInt71;
    int unkInt72;
    int unkInt73;
    int unkInt74;
    uint8_t unkPad22[3840];
    uint8_t unkPad23[7680];
    int m_zInputActions;
    int unkInt76;
    int unkInt77;
    int unkInt78;
    int unkInt79;
    int unkInt80;
    int unkInt81;
    int unkInt82;
    int unkInt83;
    uint8_t unkPad23_1[8];
    int unkInt84;
    int unkInt85;
    int unkInt86;
    uint32_t *m_engineResource;
    int m_masterProject;
    int unkInt89;
    uint8_t unkPad24[120];
    int unkInt90;
    int unkInt91;
    uint8_t unkPad25[120];
    uint8_t unkByte22;
    uint8_t m_disableTextures;
    uint8_t unkByte25;
    uint8_t m_isInitialized;
    bBool m_isMessagingEnabled;
    uint8_t m_disableConfig;
    uint8_t unkByte27;
    uint8_t unkByte28;
    int unkInt92;
    int unkInt93;
    int unkInt94;
    int unkInt95;
    int unkInt96;
    int unkInt97;
    int unkInt98;
    uint8_t unkPad26[120];
    uint8_t m_scriptDebug;
    uint8_t m_scriptDebugPrint;
    uint8_t unkPad27[2];
    float unkFloat1;
    int unkInt99;
    uint8_t unkByte30;
    uint8_t unkPad28[128];
    int unkInt100;
    int unkInt101;
    int unkInt102;
    int unkInt103;
    uint8_t m_saveRecordRuntime;
    int unkInt104;
    int unkInt105;
    int unkInt106;
    int unkInt107;
    int unkInt108;
    int m_consoleInstance;
    uint8_t unkByte31_1;
    int unkInt110;
    uint8_t m_messageFlag;
    int unkInt111;
    int unkInt112;
    uint8_t unkPad29[120];
    uint8_t m_useTryCatchLoop;
    int unkInt113;
    int m_windowTitle;
    int m_defaultTitle;
    uint8_t unkPad30[120];
    int m_emptyCharArray;
    int unkInt117;
    uint8_t unkPad31[120];
    uint8_t m_reloadEngine;
    int unkInt118;
    int unkInt119;
    float unkFloat2;
    int unkInt120;
    void *sub_FFAE110;
};

extern __declspec(dllimport) ZSysInterface *g_pSysInterface;