name: Build

on: [push, pull_request]

jobs:
    build:
        name: "MSVC 6.0"
        runs-on: "windows-latest"
        steps:
            - uses: actions/checkout@v4
            - uses: actions/checkout@v4
              with:
                  path: msvc600
                  repository: "itsmattkc/MSVC600"
                  ref: 17bae53fa330df7b576f25f1f604e4214076a650
            - name: "Build CMake project"
              shell: cmd
              run: |
                  call ${{ github.workspace }}\msvc600\VC98\Bin\VCVARS32.BAT
                  cmake -S ${{ github.workspace }} -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/bin
                  cmake --build build
            - uses: actions/upload-artifact@v4
              with:
                  name: re47-${{ github.sha }}
                  if-no-files-found: error
                  path: |
                      ${{ github.workspace }}\bin\*exe
                      ${{ github.workspace }}\bin\*dll
                      ${{ github.workspace }}\bin\*pdb
